[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[[headers]]
  for = "/css/*"
    [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
    [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "max-age=31536000, immutable"
